pkgs: binaryninja: use _7zz instead of p7zip
pkgs: binaryninja: allow dangerous symlink when unpacking
Resolves:
```
ERROR: Dangerous link path was ignored : binaryninja/python3/PySide6/Qt/plugins : ../../../qt
```